Fixed indentation issues to meet bashate compliance
Change-Id: I8c2d2a9f92027e09f033532fd2fbe9f4b6423c7a
Partially-implements: blueprint bashate-gate

diff --git a/tools/kolla b/tools/kolla
--- a/tools/kolla
+++ b/tools/kolla
@@ -22,8 +22,8 @@ function process {
     echo "$ACTION $service"
     docker-compose -f ./compose/${service}.yml $COMPOSE_CMD
     if [[ $? -ne 0 ]]; then
-       echo "Call docker-compose -f ./compose/${service}.yml $COMPOSE_CMD fail."
-       exit 1
+        echo "Call docker-compose -f ./compose/${service}.yml $COMPOSE_CMD fail."
+        exit 1
     fi
 }
 
