Check compose cmd result
Should check compse cmd excute result
can't let it go.

Change-Id: Ifd20e3b7f4ae385f7d45ab119a8850f44f254bac
Closes-Bug:#1447959

diff --git a/tools/kolla b/tools/kolla
--- a/tools/kolla
+++ b/tools/kolla
@@ -21,6 +21,10 @@ function process {
     local service=$1
     echo "$ACTION $service"
     docker-compose -f ./compose/${service}.yml $COMPOSE_CMD
+    if [[ $? -ne 0 ]]; then
+       echo "Call docker-compose -f ./compose/${service}.yml $COMPOSE_CMD fail."
+       exit 1
+    fi
 }
 
 function process_all {
