rabbitmq: Improve healthcheck script output
We've seen multiple occassions of all these healthcheck commands
not being able to be executed in 30s after the switch to RMQ 4.1.
Let's put more information in the Docker/Podman healthcheck logs.

Change-Id: I4b1b54983144f5514a6703c255d2cb4fa052a0fb
(cherry picked from commit bbe23bd107c16d4990b26e9aca5eb888f98cc781)
Signed-off-by: Maksim Malchuk <maksim.malchuk@gmail.com>

diff --git a/docker/rabbitmq/rabbitmq/healthcheck_rabbitmq b/docker/rabbitmq/rabbitmq/healthcheck_rabbitmq
--- a/docker/rabbitmq/rabbitmq/healthcheck_rabbitmq
+++ b/docker/rabbitmq/rabbitmq/healthcheck_rabbitmq
@@ -2,9 +2,7 @@
 
 set -e
 
-rabbitmq-diagnostics -t 5 -q ping || exit 1
-rabbitmq-diagnostics -t 5 -q status || exit 1
-rabbitmq-diagnostics -t 5 -q check_running || exit 1
-rabbitmq-diagnostics -t 5 -q check_local_alarms || exit 1
-rabbitmq-diagnostics -t 5 -q check_port_connectivity || exit 1
-rabbitmq-diagnostics -t 5 -q check_virtual_hosts || exit 1
+for check in ping status check_running check_local_alarms check_port_connectivity check_virtual_hosts; do
+    echo "Running rabbitmq-diagnostics $check"
+    rabbitmq-diagnostics -t 5 -q $check || (echo "ERROR: $check failed" && exit 1)
+done
